/* test_bundle.cpp: the bundle parser against the real signed fixtures.
 * The C++ parser, the vendored micro-ecc P-256 verify and the vendored
 * SHA-256 are the real device code (same sources, same configuration),
 * so a green run here is the device's own signature path, not a Python
 * re-implementation of it. The fixtures in fixtures/ were generated by
 * fw/make_bundle.py with the public development key. */
#include <stdio.h>
#include <string.h>
#include <vector>
#include "HearthBundle.h"
#include "HearthDevKey.h"

static int g_pass, g_fail;
static void check(const char *n, bool c) { printf("  [%s] %s\n", c ? "PASS" : "FAIL", n); (c ? g_pass : g_fail)++; }

class MemSource : public HearthByteSource {
public:
  std::vector<uint8_t> d;
  bool read(uint32_t off, uint8_t *buf, size_t n) override {
    if ((size_t)off + n > d.size()) return false;
    memcpy(buf, &d[off], n); return true;
  }
  uint32_t size() const override { return d.size(); }
};

static bool load(const char *path, MemSource &m) {
  FILE *f = fopen(path, "rb"); if (!f) return false;
  int c; while ((c = fgetc(f)) != EOF) m.d.push_back((uint8_t)c);
  fclose(f); return true;
}

int main() {
  MemSource m; check("fixture loads", load("fixtures/good.ota", m));
  HearthBundleInfo info;
  check("good bundle opens", HearthBundle::open(m, HEARTH_DEV_PUBKEY, info) == HEARTH_BUNDLE_OK);
  check("product version 0x10400", info.productVersion == 0x00010400u);
  check("version string", strcmp(info.productVersionString, "1.4.0") == 0);
  check("two parts", info.partCount == 2);
  check("part 0 is Hearth for the C6 wifi image", info.parts[0].type == 2 && info.parts[0].variant == 1
        && strcmp(info.parts[0].target, "ESP32-C6 Hearth") == 0 && strcmp(info.parts[0].version, "1.3.0") == 0);
  check("part 1 is the host image", info.parts[1].type == 1 && strcmp(info.parts[1].target, "product") == 0);
  check("part offsets are 16-aligned inside the container", (info.parts[0].offset % 16) == 0);
  check("part 0 digest verifies", HearthBundle::verifyPart(m, info, 0) == HEARTH_BUNDLE_OK);
  check("part 1 digest verifies", HearthBundle::verifyPart(m, info, 1) == HEARTH_BUNDLE_OK);

  MemSource bad = m; bad.d[info.containerOffset + 64 + 44] ^= 1;      // version string of row 0
  check("tampered table is a signature failure", HearthBundle::open(bad, HEARTH_DEV_PUBKEY, info) == HEARTH_BUNDLE_ERR_SIGNATURE);

  MemSource badp = m; HearthBundle::open(badp, HEARTH_DEV_PUBKEY, info);
  badp.d[info.containerOffset + info.parts[0].offset + 5] ^= 1;
  check("tampered part still opens", HearthBundle::open(badp, HEARTH_DEV_PUBKEY, info) == HEARTH_BUNDLE_OK);
  check("tampered part is a digest failure", HearthBundle::verifyPart(badp, info, 0) == HEARTH_BUNDLE_ERR_DIGEST);

  uint8_t other[64]; memcpy(other, HEARTH_DEV_PUBKEY, 64); other[3] ^= 1;
  check("wrong key is a signature failure", HearthBundle::open(m, other, info) == HEARTH_BUNDLE_ERR_SIGNATURE);

  MemSource trunc = m; trunc.d.resize(200);
  check("truncated file is a format failure", HearthBundle::open(trunc, HEARTH_DEV_PUBKEY, info) == HEARTH_BUNDLE_ERR_FORMAT);
  MemSource nomagic = m; nomagic.d[0] ^= 1;
  check("bad Matter magic is a format failure", HearthBundle::open(nomagic, HEARTH_DEV_PUBKEY, info) == HEARTH_BUNDLE_ERR_FORMAT);

  printf("test_bundle: %d passed, %d failed\n", g_pass, g_fail);
  printf("===== RESULT: %d passed, %d failed =====\n", g_pass, g_fail);
  return g_fail ? 1 : 0;
}
