# Controller's oracle generator for test/host/fixtures/xmodem_layers.txt, from the
# firmware repo's platform/silabs/fw/xmodem.py (the MG24 Gecko bootloader's sender).
# Rerun: python3 gen_xmodem_layers.py <firmware repo>/platform/silabs/fw > xmodem_layers.txt
import sys
sys.path.insert(0, sys.argv[1]); import xmodem
out = ['# Generated by the controller from the firmware repo platform/silabs/fw/xmodem.py (2026-09-29).',
       '# One case per line:',
       '#   crc <input hex or -> <crc16-xmodem, 4 hex digits>',
       '#   block <seq> <payload hex or -> <133-byte block hex>   (build_block(seq, payload, 128): SOH, seq, ~seq, 128 bytes padded 0x1A, crc16 big-endian)',
       '#   image <image hex>                        the image a transcript line uploads',
       '#   tx <hex>                                  every byte a correct upload of that image writes: "1", the blocks in order, EOT, "2"']
for data in [b'', b'123456789', bytes(range(16)), b'\x1a' * 128]:
    out.append('crc %s %04X' % (data.hex() or '-', xmodem.crc16_xmodem(data)))
cases = [(1, bytes(range(128))), (2, b'short'), (3, b''), (255, b'\xff' * 10), (256, b'wrap')]
for seq, p in cases:
    out.append('block %d %s %s' % (seq, p.hex() or '-', xmodem.build_block(seq, p, 128).hex()))
image = bytes((i * 7 + 3) & 0xFF for i in range(300))   # 3 blocks, the last one 44 bytes
tx = b'1' + b''.join(xmodem.build_block((i // 128 + 1) & 0xFF, image[i:i + 128], 128) for i in range(0, len(image), 128)) + bytes([xmodem.EOT]) + b'2'
out.append('image ' + image.hex())
out.append('tx ' + tx.hex())
print('\n'.join(out))
