# Controller's oracle generator for test/host/fixtures/smp_layers.txt (rerun: python3 gen_smp_layers.py <fw dir> > fixture).
import sys, base64
sys.path.insert(0, sys.argv[1]); import smp
out = ['# Generated by the controller from the firmware repo platform/nrf54l15/fw/smp.py (2026-09-29).',
       '# Layered SMP oracles, one case per line:',
       '#   crc <input hex or -> <crc16-xmodem, 4 hex digits>',
       '#   frame <frame hex> <padding count> <n> then n lines "line <text>" (serial_encode output; <06><09><04><14> are the start bytes)',
       '#   cbor <cbor hex> <rc or -> <off or ->   (smp.cbor_decode; - = key absent)']
for data in [b'', b'123456789', bytes(range(16)), b'\x00' * 37]:
    out.append('crc %s %04X' % (data.hex() or '-', smp.crc16_xmodem(data)))
for n in (2, 0, 3, 300):   # base64 padding 0, 1, 2, and a multi-line frame
    payload = {'rc': 0} if n == 0 else {'d': 'x' * n}
    fr = smp.encode_frame(3, 1, 1, payload, 7)
    lines = [l for l in smp.serial_encode(fr).split(b'\n') if l]
    pad = sum(l.count(b'=') for l in lines)
    out.append('frame %s %d %d' % (fr.hex(), pad, len(lines)))
    for l in lines:
        out.append('line ' + l.decode('latin-1').replace('\x06', '<06>').replace('\x09', '<09>').replace('\x04', '<04>').replace('\x14', '<14>'))
for h in ('a262726300636f66661901c0', 'bf62726300636f66661901c0ff', 'bf62726303ff', 'bf62726308636f6666190258ff'):
    m = smp.cbor_decode(bytes.fromhex(h))
    out.append('cbor %s %s %s' % (h, m.get('rc', '-'), m.get('off', '-')))
print('\n'.join(out))
