# Controller's oracle generator for test/host/fixtures/esp_layers.txt, from esptool
# (the reference client of the ESP ROM download loader), run under ESP-IDF's python.
# Rerun: ~/.espressif/python_env/idf5.4_py3.12_env/bin/python gen_esp_layers.py > esp_layers.txt
import struct
import esptool
from esptool.loader import ESPLoader

class Capture:
    def __init__(self): self.buf = b''
    def write(self, b): self.buf += b

def wire(op, data, chk=0):
    """The bytes esptool's ESPLoader.command() puts on the UART for one request."""
    loader = ESPLoader.__new__(ESPLoader)
    loader._port = Capture()
    loader._trace_enabled = False
    ESPLoader.write(loader, struct.pack(b'<BBHI', 0x00, op, len(data), chk) + data)
    return loader._port.buf

sync = wire(ESPLoader.ESP_SYNC, b'\x07\x07\x12\x20' + 32 * b'\x55')
out = ['# Generated by the controller from esptool %s (2026-09-29).' % esptool.__version__,
       '# One case per line:',
       '#   sync <hex>        the SLIP-framed SYNC request, the first thing a ROM connect writes',
       '#   silent <n> <hex>  everything a connect with trials=n writes to a target that never answers:',
       '#                     n SYNC requests back to back and nothing else',
       'sync ' + sync.hex(),
       'silent 10 ' + (sync * 10).hex()]
print('\n'.join(out))
