# Controller's oracle generator for test/host/fixtures/apply_parts.txt: where each
# part of the signed fixtures sits inside the staged file (the whole .ota as
# downloaded), from fw/hearth_bundle.py, the reference the fixtures were built with.
# Rerun from the repo root: python3 test/host/fixtures/gen_apply_parts.py > test/host/fixtures/apply_parts.txt
import hashlib, os, sys
sys.path.insert(0, 'fw')
import hearth_bundle as hb

out = ['# Generated by the controller from fw/hearth_bundle.py (2026-09-29).',
       '# Fields are separated by "|".',
       '#   bundle|<fixture>|<containerOffset>|<product version u32>|<product version string>',
       '#   part|<fixture>|<index>|<type 1 host, 2 Hearth>|<target>|<variant 0 none, 1 wifi, 2 thread, 3 combined>|<version>|<staged offset>|<length>|<sha256 hex>',
       '# <staged offset> is containerOffset + the part table offset: the byte offset inside the',
       '# staged file that a flasher (or PicoOTA addFile) is handed.']
for name in ('good', 'nrf-only'):
    blob = open(os.path.join('test/host/fixtures', name + '.ota'), 'rb').read()
    _info, payload = hb.unwrap_ota(blob)
    co = len(blob) - len(payload)
    c = hb.parse_container(payload)
    out.append('bundle|%s|%d|%d|%s' % (name, co, c['product_version'], c['product_version_string']))
    for i, p in enumerate(c['parts']):
        body = payload[p['offset']:p['offset'] + p['length']]
        assert hashlib.sha256(body).digest() == p['sha256']
        assert blob[co + p['offset']:co + p['offset'] + p['length']] == body
        out.append('part|%s|%d|%d|%s|%s|%s|%d|%d|%s' % (name, i, p['type'], p['target'], p['variant'],
                   p['version'], co + p['offset'], p['length'], p['sha256'].hex()))
print('\n'.join(out))
