"""
hearth_bundle.py: the Hearth firmware bundle (spec 2026-09-07-fota-design,
section 3) as a Python module. Stdlib plus the `openssl` command line for
the ECDSA P-256 signature, so a product build needs nothing installed.

Container: 64-byte header, 108-byte parts table rows, a 64-byte raw r||s
ECDSA signature over SHA-256(header || table), then the parts at 16-byte
aligned offsets. Wrapped in a standard Matter OTA header for delivery.
"""
import hashlib
import os
import struct
import subprocess

MAGIC = b"HRTHBNDL"
FORMAT = 1
HEADER = struct.Struct("<8sHHHHI32sBB10s")   # 64 bytes
PART = struct.Struct("<BBHII32s32s32s")       # 108 bytes
SIG_LEN = 64
PART_HOST = 1
PART_HEARTH = 2
VARIANT = {"none": 0, "wifi": 1, "thread": 2, "combined": 3}
ALIGN = 16


def _cstr(s, n):
    b = s.encode()
    if len(b) >= n:
        raise ValueError("string %r longer than %d bytes" % (s, n - 1))
    return b.ljust(n, b"\0")


def _unc(b):
    return b.split(b"\0", 1)[0].decode()


def _openssl(args, data):
    return subprocess.run(["openssl"] + args, input=data, check=True,
                          stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout


def _der_to_raw(der):
    """DER SEQUENCE { INTEGER r, INTEGER s } -> 64-byte r||s."""
    assert der[0] == 0x30
    i = 2 if der[1] < 0x80 else 3
    out = b""
    for _ in range(2):
        assert der[i] == 0x02
        n = der[i + 1]
        v = der[i + 2:i + 2 + n].lstrip(b"\0")
        out += v.rjust(32, b"\0")
        i += 2 + n
    return out


def _raw_to_der(raw):
    def integer(v):
        v = v.lstrip(b"\0") or b"\0"
        if v[0] & 0x80:
            v = b"\0" + v
        return bytes([0x02, len(v)]) + v
    body = integer(raw[:32]) + integer(raw[32:])
    return bytes([0x30, len(body)]) + body


def sign(data, key_pem):
    return _der_to_raw(_openssl(["dgst", "-sha256", "-sign", key_pem], data))


def verify(data, sig_raw, pub_pem):
    with_sig = _raw_to_der(sig_raw)
    tmp = pub_pem + ".sig.tmp"
    with open(tmp, "wb") as f:
        f.write(with_sig)
    try:
        r = subprocess.run(["openssl", "dgst", "-sha256", "-verify", pub_pem, "-signature", tmp],
                           input=data, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        return r.returncode == 0
    finally:
        os.unlink(tmp)


def pubkey_raw(pub_pem):
    """The 64-byte X||Y of a P-256 public key (the DER SubjectPublicKeyInfo
    ends with 0x04 || X || Y)."""
    der = _openssl(["ec", "-pubin", "-in", pub_pem, "-outform", "DER"], b"")
    assert der[-65] == 0x04
    return der[-64:]


def emit_dev_key_header(pub_pem, path):
    raw = pubkey_raw(pub_pem)
    lines = ["/* Generated by fw/hearth_bundle.py from %s. The development key is",
             " * public: it gives integrity, not authenticity. A product compiles in",
             " * its own key (HearthUpdateConfig::publicKey). */",
             "#pragma once", "#include <stdint.h>",
             "static const uint8_t HEARTH_DEV_PUBKEY[64] = {"]
    for i in range(0, 64, 8):
        lines.append("    " + ", ".join("0x%02X" % b for b in raw[i:i + 8]) + ",")
    lines.append("};")
    with open(path, "w") as f:
        f.write("\n".join(lines).replace(os.path.dirname(pub_pem) + "/", "") + "\n")


def build_container(vendor, product, version, version_str, parts, key_pem):
    if not 1 <= len(parts) <= 2:
        raise ValueError("one or two parts")
    table_len = PART.size * len(parts)
    off = HEADER.size + table_len + SIG_LEN
    rows, blobs = [], []
    for p in parts:
        off = (off + ALIGN - 1) // ALIGN * ALIGN
        data = p["data"]
        rows.append(PART.pack(p["type"], p.get("variant", 0), p.get("flags", 0), off, len(data),
                              _cstr(p["target"], 32), _cstr(p["version"], 32),
                              hashlib.sha256(data).digest()))
        blobs.append((off, data))
        off += len(data)
    header = HEADER.pack(MAGIC, FORMAT, HEADER.size, vendor, product, version,
                         _cstr(version_str, 32), len(parts), 0, b"\0" * 10)
    table = b"".join(rows)
    sig = sign(header + table, key_pem)
    out = bytearray(header + table + sig)
    for o, data in blobs:
        out += b"\0" * (o - len(out))
        out += data
    return bytes(out)


def parse_container(blob):
    if len(blob) < HEADER.size:
        raise ValueError("too short")
    magic, fmt, hlen, vendor, product, version, vstr, count, _flags, _r = HEADER.unpack_from(blob, 0)
    if magic != MAGIC or fmt != FORMAT or hlen != HEADER.size or not 1 <= count <= 2:
        raise ValueError("not a Hearth bundle")
    parts = []
    for i in range(count):
        t, var, flags, off, length, target, ver, sha = PART.unpack_from(blob, HEADER.size + i * PART.size)
        if off + length > len(blob):
            raise ValueError("part %d beyond the end" % i)
        parts.append({"type": t, "variant": var, "flags": flags, "offset": off, "length": length,
                      "target": _unc(target), "version": _unc(ver), "sha256": sha})
    sig_off = HEADER.size + count * PART.size
    return {"vendor_id": vendor, "product_id": product, "product_version": version,
            "product_version_string": _unc(vstr), "parts": parts,
            "signature": blob[sig_off:sig_off + SIG_LEN], "signed_len": sig_off}


def verify_container(blob, pub_pem):
    info = parse_container(blob)
    return verify(blob[:info["signed_len"]], info["signature"], pub_pem)


def verify_parts(blob):
    info = parse_container(blob)
    return all(hashlib.sha256(blob[p["offset"]:p["offset"] + p["length"]]).digest() == p["sha256"]
               for p in info["parts"])


# ---- the Matter OTA header (ota_image_tool.py's layout) ---------------------

OTA_MAGIC = 0x1BEEF11E
OTA_FIXED = struct.Struct("<IQI")


def _tlv_uint(tag, value):
    for ctl, fmt in ((0x04, "<B"), (0x05, "<H"), (0x06, "<I"), (0x07, "<Q")):
        try:
            return bytes([0x20 | ctl, tag]) + struct.pack(fmt, value)
        except struct.error:
            continue
    raise ValueError(value)


def _tlv_str(tag, s):
    b = s.encode()
    return bytes([0x2C, tag, len(b)]) + b


def _tlv_bytes(tag, b):
    return bytes([0x30, tag, len(b)]) + b


def wrap_ota(payload, vendor, product, version, version_str):
    tlv = (bytes([0x15]) + _tlv_uint(0, vendor) + _tlv_uint(1, product) + _tlv_uint(2, version)
           + _tlv_str(3, version_str) + _tlv_uint(4, len(payload)) + _tlv_uint(8, 1)
           + _tlv_bytes(9, hashlib.sha256(payload).digest()) + bytes([0x18]))
    return OTA_FIXED.pack(OTA_MAGIC, OTA_FIXED.size + len(tlv) + len(payload), len(tlv)) + tlv + payload


def unwrap_ota(blob):
    magic, total, hlen = OTA_FIXED.unpack_from(blob, 0)
    if magic != OTA_MAGIC or total != len(blob):
        raise ValueError("not a Matter OTA image")
    tlv = blob[OTA_FIXED.size:OTA_FIXED.size + hlen]
    info, i = {}, 1                                   # skip the 0x15 structure open
    names = {0: "vendor_id", 1: "product_id", 2: "version", 3: "version_string", 4: "payload_size",
             5: "min_version", 6: "max_version", 7: "release_notes", 8: "digest_type", 9: "digest"}
    while tlv[i] != 0x18:
        ctl, tag = tlv[i], tlv[i + 1]
        elem = ctl & 0x1F
        i += 2
        if elem in (0x04, 0x05, 0x06, 0x07):
            n = {0x04: 1, 0x05: 2, 0x06: 4, 0x07: 8}[elem]
            info[names[tag]] = int.from_bytes(tlv[i:i + n], "little"); i += n
        elif elem in (0x0C, 0x10):                    # utf-8 / octet string, 1-byte length
            n = tlv[i]; i += 1
            v = tlv[i:i + n]; i += n
            info[names[tag]] = v.decode() if elem == 0x0C else v
        else:
            raise ValueError("unexpected TLV element 0x%02X" % ctl)
    return info, blob[OTA_FIXED.size + hlen:]
